- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/model/response/UserAuthenticatedMeResponse.java
- src/main/java/com/alkemy/ong/service/RoleServiceImpl.java
- src/main/java/com/alkemy/ong/service/UserServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IAuthenticatedUserDetails.java
agregue endpoint para obtener los datos del usuario autenticado. Y agregue un DTO para pasar esos datos filtrados.
> OT98-36: Endpoint datos usuario autenticado

- pom.xml
- src/main/java/com/alkemy/ong/config/AmazonConfig.java
- src/main/resources/application.yaml
Amazon dependency added to pom, yml file with amazon properties created & amazon config class also created
> Ot98-38: Setup Amazon S3 SDK

- README.md
- pom.xml
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/config/SwaggerConfig.java
- src/main/resources/application.properties
- src/main/resources/application.yaml
- src/test/java/com/alkemy/ong/integration/UserRegisterIntegrationTest.java
- src/test/resources/application.yaml
Sumarry: 
-add dependencies for swagger.
-add configuration file.
-add url to security.
> OT98-84: Agregar documentacion con Swagger

- src/main/java/com/alkemy/ong/model/response/OrganizationResponse.java
- src/main/java/com/alkemy/ong/service/OrganizationServiceImpl.java
Organization´s Social media information was added to the endpoint. It will be shown only if it isn´t null
> OT98-64: Modificar endpoint público de organizations para devolver links de redes sociales

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/common/converter/ConvertUtils.java
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/ActivityController.java
- src/main/java/com/alkemy/ong/model/request/CreateActivityRequest.java
- src/main/java/com/alkemy/ong/model/response/CreateActivityResponse.java
- src/main/java/com/alkemy/ong/repository/IActivityRepository.java
- src/main/java/com/alkemy/ong/service/ActivityServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/ICreateActivityService.java
agrego endpoint creacion de actividades y adjunto evidencia
> OT98 50 Endpoint Creación Actividades

- src/main/java/com/alkemy/ong/model/entity/Comment.java
Agrego la entidad Comment, el repositorio y el servicio pedidos. Y también los dtos. El scope del ticket no me quedo muy claro, hice lo que comprendí que el ticket requería.
> OT98 74 Crear modelo, repositorio y servicio de Comentarios

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/common/converter/ConvertUtils.java
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/model/response/DetailsContactResponse.java
- src/main/java/com/alkemy/ong/model/response/ListContactResponse.java
- src/main/java/com/alkemy/ong/repository/IContactRepository.java
- src/main/java/com/alkemy/ong/service/ContactServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IListContactsService.java
Sumary: 
- add repository and interface to list contacts
- add service implementation 
- add endpoint to list contacts, only admins can do this.
if i tried with an user
> OT98 61: Endpoint para listar contactos 

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/common/PaginatedResultsHeaderUtils.java
- src/main/java/com/alkemy/ong/common/converter/ConvertUtils.java
- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/exception/ErrorHandler.java
- src/main/java/com/alkemy/ong/exception/PageOutOfRangeException.java
- src/main/java/com/alkemy/ong/model/response/ListNewsResponse.java
- src/main/java/com/alkemy/ong/repository/INewsRepository.java
- src/main/java/com/alkemy/ong/service/NewsServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IListNewsService.java
Se agrega el endpoint para listar las novedades, el mismo está paginado según los requirimentos del ticket.
Se agrega "Link" en los headers con los links a la página siguiente y anterior (en caso de que estos existan).
Pagina fuera de rango
Ok response body
Ok response header
> OT98-81 Add pagination to news

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/common/converter/ConvertUtils.java
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/model/response/DetailsMemberResponse.java
- src/main/java/com/alkemy/ong/model/response/ListMemberResponse.java
- src/main/java/com/alkemy/ong/repository/IMemberRepository.java
- src/main/java/com/alkemy/ong/service/MemberServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IListMembersService.java
Summary:
-add method in repository that find members with softDelete equals False.
-add services, responses and controller to members
-add routes to security
Evidense:
> OT98-68: Endpoint para listar miembros

- src/main/java/com/alkemy/ong/config/seeder/ActivitiesSeeder.java
> OT98-52: Crear Seed Data para guardar actividades existentes de la ONG

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IDeleteSlide.java
- src/main/java/com/alkemy/ong/service/abstraction/IDeleteSlideService.java
> OT98-59: Endpoint Delete Slide

- src/main/java/com/alkemy/ong/common/mail/template/RegisterTemplateEmail.java
Summary: 
- Add email template for register.
- The Email will send in the ticket number 30.
> OT98-29: Integrar template de email de bienvenida

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/model/request/CategoryUpdateRequest.java
- src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IUpdateCategoryService.java
Summary:
- add endpoint update categories.
- only admins can update categories.
- if the id doesnt exist throw a message error.
> OT98-43: Endpoint Actualización Categorías

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/common/converter/ConvertUtils.java
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/model/response/DetailsSlideResponse.java
- src/main/java/com/alkemy/ong/model/response/ListSlidesResponse.java
- src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IListSlidesService.java
Se agrega el endpoint para listar los slides. Se crean las responses necesarias.
Se agregan los roles necesarios para poder acceder al endpoint.
> OT98-55: Endpoint list slide

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/exception/ErrorHandler.java
- src/main/java/com/alkemy/ong/service/TestimonialServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IDeleteTestimonialService.java
COMO usuario administrador
QUIERO eliminar testimonios
PARA moderar los testimonios y novedades acerca de la ONG.
Criterios de aceptación:
DELETE /testimonials/:id - Deberá validar que el testimonio existe y eliminarlo, caso contrario devolver un error
Evidencia 1
Evidencia 2
> OT98-67: Endpoint eliminación de Testimonios

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IDeleteCategoryService.java
Delete categories endpoint implemented and added to security config. 
IDeleteCategoryService implemented on CategoryServiceImpl.
Postman collection included.
> OT98-44: endpoint Eliminación Categorías

- etc/postman/OT-98.postman_collection.json
Se agrega un pre request script a la postman collection y las varaibles adminJWT y userJWT para poder utilizarlas en las authenticaciones sin la necesidad de logearse cada vez y solucionando el problema que tenía actualmente la collection que es el vencimiento del jwt harcodeado en las variables.
> Postman authentication script

- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/model/request/CreateContactRequest.java
- src/test/java/com/alkemy/ong/integration/contact/AbstractBaseContactIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/contact/CreateContactIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/contact/ListContactIntegrationTest.java
Se agrego validacion de @Email en CreateContactRequest
Se agrego validacion de @Valid en ContactController
Se agrego file con tests de Contact (AbstractBaseContactIntegrationTest, CreateContactIntegrationTest, ListContactIntegrationTest)
> OT98 95 Test: Endpoints /contact

- src/main/java/com/alkemy/ong/controller/ActivityController.java
- src/test/java/com/alkemy/ong/integration/activity/AbstractBaseActivityIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/activity/CreateActivityIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/activity/UpdateActivityIntegrationTest.java
Summary:
- add test to create activity:
- add test to update activity:
> OT98-94 :  Test: Endpoints /activities

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/repository/ICategoryRepository.java
- src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IListCategoryService.java
Pagination to List of Categories endpoint added. 
Modifications were made on findBySoftDeleteFalse method at CategoryRepository, findAll method at IListCategoryService and CategoryServiceImpl, and also on findAllCategories at CategoryController.
Postman Collection changes added.
> OT98-80: agregar paginación a categorías

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/service/MemberServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IUpdateMembersService.java
PUT member route to SecurityConfig added.
postmanCollection updated.
update method to MemberController added.
update method to MemberServiceImpl  added. 
IUpdateMembersService interface created.
attaching evidence from ticket 71.
> OT98 71: Endpoint Actualización miembros

- src/main/java/com/alkemy/ong/common/messages/DocumentationMessages.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
Summary:
- add documentation to member controller
> OT98-87: Agregar documentación a Miembros

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/common/converter/ConvertUtils.java
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/model/entity/Comment.java
- src/main/java/com/alkemy/ong/model/response/CommentsResponse.java
- src/main/java/com/alkemy/ong/model/response/ListCommentsResponse.java
- src/main/java/com/alkemy/ong/repository/ICommentRepository.java
- src/main/java/com/alkemy/ong/service/CommentServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IListCommentsService.java
endpoint created, postman added
> OT98-75: Endpoint para listar comentarios

- src/test/java/com/alkemy/ong/common/ListTestUtils.java
- src/test/java/com/alkemy/ong/common/PaginationUtils.java
- src/test/java/com/alkemy/ong/integration/member/AbstractBaseMemberIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/member/CreateMemberIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/member/DeleteMemberIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/member/ListMemberIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/member/UpdateMemberIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/news/ListNewsIntegrationTest.java
se agrego la carpeta de tests de member
> OT98-91: adding integration member file

- src/test/java/com/alkemy/ong/integration/user/AbstractBaseUserIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/user/AuthenticatedUserDetailsIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/user/DeleteUserIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/user/ListUserIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/user/UpdateUserIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/user/UserAuthenticationIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/user/UserRegisterIntegrationTest.java
Summary:
- add test for endpoints /user.
- Endpoint delete user by id:
- Endpoint update user by id:
- Endpoint list users:
> OT98-90: Test: Endpoints /users

- src/main/java/com/alkemy/ong/common/messages/DocumentationMessages.java
- src/main/java/com/alkemy/ong/controller/AuthenticationController.java
- src/main/java/com/alkemy/ong/controller/UserController.java
Se agrego documentacion del endpoint de autenticacion
> OT98-89 Agregar documentación a Autenticación

- src/main/java/com/alkemy/ong/common/messages/DocumentationMessages.java
- src/main/java/com/alkemy/ong/controller/CategoryController.java
Documentation for Category endpoints added.
Messages added to DocumentationMessages.
> OT98-85: agregar documentación a Categorías

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/service/TestimonialServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IUpdateTestimonialService.java
COMO usuario administrador
QUIERO actualizar los testimonios
PARA informar nuevas novedades acerca de la ONG.
Criterios de aceptación:
PUT /testimonials/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista, deberá devolver un error, mientras que en caso contrario, deberá actualizarla y devolverla con los datos nuevos.
Evidencia 1:
Evidencia 2:
> OT98-66: Endpoint Actualización Testimonios

- src/main/java/com/alkemy/ong/common/messages/DocumentationMessages.java
- src/main/java/com/alkemy/ong/controller/TestimonialController.java
Se agrega la documentación a testimonials y los mensajes utilizados.
La response del método deletBy fue modificada para evitar la response genérica.
> OT98-88: add documentation to testimonials

- src/test/java/com/alkemy/ong/integration/category/AbstractBaseCategoryIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/category/CreateCategoryIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/category/DeleteCategoryIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/category/GetCategoryIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/category/ListCategoryIntegrationTest.java
- src/test/java/com/alkemy/ong/integration/category/UpdateCategoryIntegrationTest.java
Testing for Category endpoints implemented.
The endpoints tested were: 
- create in CreateCategoryIntegrationTest
- findAllCategories in ListCategoryIntegrationTest
- getCategoryDetails in GetCategoryIntegrationTest
- update in UpdateCategoryIntegrationTest
- deleteBy in DeleteCategoryIntegrationTest
> OT98-97: Test: Endpoints /categories

- etc/postman/OT-98.postman_collection.json
- src/main/java/com/alkemy/ong/config/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/model/response/CommentDetailsResponse.java
- src/main/java/com/alkemy/ong/model/response/NewsDetailsCommentsResponse.java
- src/main/java/com/alkemy/ong/repository/ICommentRepository.java
- src/main/java/com/alkemy/ong/repository/INewsRepository.java
- src/main/java/com/alkemy/ong/service/CommentServiceImpl.java
- src/main/java/com/alkemy/ong/service/abstraction/IListCommentsService.java
- src/main/java/com/alkemy/ong/service/abstraction/IListNewsService.java
> OT98-79: Endpoint para listar comentarios en base a un post
